name: Proxy Checker API

on:
  repository_dispatch:  # Memicu GitHub Actions saat ada request dari Cloudflare Workers

jobs:
  check-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Ganti dengan versi Python yang Anda inginkan

      - name: Install dependencies
        run: pip install pycountry

      - name: Run Python script
        run: |
          python main.py ${{ github.event.client_payload.ip }}

      - name: Commit and push results
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${GH_TOKEN}@github.com/donghuaaa/testing.git
          git add result.json
          git commit -m "Update result.json" || echo "No changes to commit"
          git push origin main || echo "Push failed"
